export const actions = {
    newUserActions: {
        NEW_USER_FIRST_NAME: 'NEW_USER_FIRST_NAME',
        NEW_USER_LAST_NAME: 'NEW_USER_LAST_NAME',
        NEW_USER_EMAIL: 'NEW_USER_EMAIL',
        NEW_USER_PASSWORD: 'NEW_USER_PASSWORD',
        NEW_USER_CC_NAME: 'NEW_USER_CC_NAME',
        NEW_USER_CC_NUMBER: 'NEW_USER_CC_NUMBER',
        NEW_USER_CC_EXPIRY: 'NEW_USER_CC_EXPIRY',
        NEW_USER_CC_SECCODE: 'NEW_USER_CC_SECCODE'
    },
    accountActions: {
        CREATE_ACCOUNT: 'CREATE_ACCOUNT',
        READ_ACCOUNT: 'READ_ACCOUNT',
        SET_ACOUNT: 'SET_ACCOUNT',
    },
    userActions: {
        CREATE_USER: 'CREATE_USER',
        READ_USER: 'READ_USER',
        UPDATE_USER: 'UPDATE_USER',
        DELETE_USER: 'DELETE_USER',
        AUTH_USER: 'AUTH_USER',
    }
}