export const initialState = {
    message: 'Hello World',
    newUserData: {
        firstName: '',
        lastName: '',
        email: '',
        password: '',
        ccName: '',
        cc: 0,
        expiry: '',
        securityCode: 0,
    },
    accountData: {},
    assetData: {},
    clientData: {},
    claim: {},
    policy: {},
    note: {},
    userData: {},
}